[workspace]
resolver = "2"
members = [
    "crates/vtd-protocol",
    "crates/vtd-libum",
    "crates/vtd-libum-ffi",
    "crates/vtd-metrics",

    "drivers/driver-usermode",
]

[workspace.package]
edition = "2024"
